a = input('Digite algo: ')
print('o tipo primitivo desse valor é:', type(a))
print('É um número?', a.isnumeric())
print('Só tem espaços?', a.isspace())
print('É alfabetico?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('As letras são apenas maiusculas?', a.isupper())
print('As letras são apenas minusculas?', a.islower())
print('Está capitalizada?', a.istitle())
