n1 = input('Digite um numero: ')
print('o valor multiplicado por 1 é igual a {}'.format(int(n1) * 1))
print('o valor multiplicado por 2 é igual a {}'.format(int(n1) * 2))
print('o valor multiplicado por 3 é igual a {}'.format(int(n1) * 3))
print('o valor multiplicado por 4 é igual a {}'.format(int(n1) * 4))
print('o valor multiplicado por 5 é igual a {}'.format(int(n1) * 5))
print('o valor multiplicado por 6 é igual a {}'.format(int(n1) * 6))
print('o valor multiplicado por 7 é igual a {}'.format(int(n1) * 7))
print('o valor multiplicado por 8 é igual a {}'.format(int(n1) * 8))
print('o valor multiplicado por 9 é igual a {}'.format(int(n1) * 9))
print('o valor multiplicado por 10 é igual a {}'.format(int(n1) * 10))
