n1 = input('Digite um valor: ')
n2 = input('Digite outro valor: ')
s = int(n1) + int(n2)
m = int(n1) * int(n2)
d = int(n1) / int(n2)
di = int(n1) // int(n2)
e = int(n1) ** int(n2)
print('a soma é {},\n a multiplicação é {},\n a divisão é {}'.format(s, m, d), end=' ')
print(' a divisão inteira é {},\n a exponencial é {}'.format(di, e))
